---
title: "Data Science for Statisticians"
author: "Stephanie Hicks, Rafael Irizarry"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

Welcome to Data Science for Statisticians at JSM 2018! [Please fill out this poll](https://docs.google.com/forms/d/e/1FAIpQLSeeSTMKCfBeXRe8p_2TYq5RrdEE80j4coI2vrEt2EDKQcd7iA/viewform?usp=sf_link)

## Course outline

* [What do we mean by data science? What are our guiding principles when teaching data science?](https://docs.google.com/presentation/d/1chQXLcLdPEXx-iC58fh1XHCAmLN5Q6rOt8eZvMvcbOo/edit?usp=sharing)
* Getting set up
  * [Installing R, RStudio and Git](productivity/installing-software.html)
  * [Working in RStudio](productivity/rstudio.html)
  * [Working in Unix](productivity/unix.html)
  * [Advanced Unix](productivity/advanced-unix.html)
  * [Introduction to Git](productivity/git.html)
  * [Introduction to GitHub](productivity/github.html)
* [Wrangling with the tidyverse](lectures/01-basic-data-wrangling.html)
* [Data visualization with ggplot2](lectures/02-intro-to-ggplot2.html)
* Example lectures and case studies
  * [Trends in world health and economics - Data visualization](lectures/03-gapminder.html)
  * [Data visualization principles](lectures/04-dataviz-principles.html)
  * [Election forecasting - Statistical Inference and Modeling](lectures/05-election-forecasting.html)
  * [Advanced wrangling](lectures/06-wrangling.html)
  * [Zip code reading - Machine Learning](lectures/07-machine-learning.html)
  * [Smoothing](lectures/08-smoothing.html)
  * [Advanced machine learning](lectures/09-machine-learning-2.html)
* [Logistics for our course](course_logistics/course_logistics.html)
* Practicum: create your own homework

